main: com.cyberfox.offlineplayer.OfflinePlayerPlugin
name: OfflinePlayer
version: ${project.version}
website: http://www.cyberfox.com
authors: [confuserr, cyberfox]
depend: [WorldEdit]
commands:
  xoffline:
    description: "XOffline base command"
    usage: "/<command> <subCommand> <args>"
